version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: 'dev.feature.depend-pull'
    assignees:
      - "stark81"
    reviewers:
      - "stark81"
    open-pull-requests-limit: 5
    versioning-strategy: increase
